#!/bin/bash
if [ ! -d lp ]; then
	mkdir lp
	cd lp
	repo init -u https://android.googlesource.com/platform/manifest.git -b android-5.1.1_r38 --depth=1
else
	cd lp
fi
echo "Downloading AOSP..."
if ! repo sync --force-sync --no-clone-bundle --no-tags -j2; then
	echo "Error syncing AOSP repo. Network having a stroke?"
	cd ~
	exit
fi
if [ -e "./prebuilts/misc/linux-x86/ccache/ccache" ]; then
	echo "Setting up ccache..."
	echo "export USE_CCACHE=1" >> ~/.bashrc
	./prebuilts/misc/linux-x86/ccache/ccache -M 50G
fi
echo "Cloning test device tree..."
cd device
mkdir mlx
cd mlx
git clone https://github.com/MLXProjects/android_device_mlx_test mlx_test --depth=1
cd ~
